music_directory     "/home/ritch/Music"
playlist_directory  "/home/ritch/.config/mpd/playlists"

db_file             "/home/ritch/.local/state/mpd/database"
log_file            "/home/ritch/.local/state/mpd/log"
pid_file            "/home/ritch/.local/state/mpd/pid"
state_file          "/home/ritch/.local/state/mpd/state"

bind_to_address     "127.0.0.1"
port                "6600"

auto_update         "yes"

audio_output {
    type "pipewire"
    name "PipeWire"
}
