function __lnx_df_item_icon --argument-names key
  switch $key
    case '.folder'
      printf '\ue5ff'
    case '.png' '.jpg' '.jpeg' '.webp' '.gif' '.ico'
      printf '\uf03e'
    case '.mkv' '.mp4' '.mov' '.avi' '.webm' '.flv'
      printf '\uf03d'
    case '.ogg' '.wav' '.mp3' '.m4a' '.flac' '.aac' '.aiff'
      printf '\uf001'
    case '.zip' '.rar' '.7z'
      printf '\uf410'
    case '.exe' '.msi'
      printf '\ue70f'
    case '.pdf'
      printf '\uf1c1'
    case '.doc' '.docx'
      printf '\uf1c2'
    case '.xls' '.xlsx' '.xml' '.csv'
      printf '\uf1c3'
    case '.ps1'
      printf '\ue86c'
    case '.bat'
      printf '\uf489'
    case '.sh' '.zsh' '.zshrc'
      printf '\ue691'
    case '.conf'
      printf '\uf013'
    case '.md'
      printf '\u039b'
    case '.gitignore' '.gitattributes' '.git'
      printf '\ue702'
    case '.js' '.jsx' '.json' '.jsonc'
      printf '\ued0d'
    case '.lua'
      printf '\ue620'
    case '.cmakelists'
      printf '\ue673'
    case '.c' '.clangd' '.cpp' '.h'
      printf '\ue61e'
    case '.rs' '.toml' '.lock'
      printf '\ue7a8'
    case '.cs' '.csproj' '.sln'
      printf '\ue7b2'
    case '.go' '.mod' '.sum'
      printf '\ue627'
    case '.sql' '.psql'
      printf '\ue76e'
    case readme
      printf '\ueda4'
    case license
      printf '\ue60a'
    case '*'
      printf '\uf0f6'
  end
end
