-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- This is an example Hyprland config file.

-- Refer to the wiki for more information.

-- https://wiki.hypr.land/Configuring/

-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

-- You can split this configuration into multiple files

-- Create your files separately and then link them to this file like this:

-- source = ~/.config/hypr/myColors.conf

--###############

--## MONITORS ###

--###############

-- See https://wiki.hypr.land/Configuring/Monitors/

--monitor=,preferred,auto,auto

hl.monitor({
    output   = "DP-2",
    mode     = "1920x1080@100",
    position = "0x0",
    scale    = 1,
})

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1366x768@59.79",
    position = "1920x0",
    scale    = 1,
})

-- Workspaces independientes por monitor con IDs UNICOS (la TV TCL es 720p nativa, no puede con 1080p real)

-- DP-2 (principal): 1-10 | HDMI-A-1 (TV): 11-20 con defaultName 1-10 (prefijo ZWSP U+200B para

-- que waybar muestre numeracion local sin colisionar con los nombres del DP).

-- OJO: Hyprland no permite el mismo ID persistente en dos monitores (las reglas por rango/ID

-- se pisan entre si), por eso el offset del HDMI.

hl.workspace_rule({
    workspace = 1,
    monitor = "DP-2",
    persistent = true,
})

hl.workspace_rule({
    workspace = 2,
    monitor = "DP-2",
    persistent = true,
})

hl.workspace_rule({
    workspace = 3,
    monitor = "DP-2",
    persistent = true,
})

hl.workspace_rule({
    workspace = 4,
    monitor = "DP-2",
    persistent = true,
})

hl.workspace_rule({
    workspace = 5,
    monitor = "DP-2",
    persistent = true,
})

hl.workspace_rule({
    workspace = 6,
    monitor = "DP-2",
})

hl.workspace_rule({
    workspace = 7,
    monitor = "DP-2",
})

hl.workspace_rule({
    workspace = 8,
    monitor = "DP-2",
})

hl.workspace_rule({
    workspace = 9,
    monitor = "DP-2",
})

hl.workspace_rule({
    workspace = 10,
    monitor = "DP-2",
})

hl.workspace_rule({
    workspace = 11,
    monitor = "HDMI-A-1",
    persistent = true,
    default_name = "​1",
})

hl.workspace_rule({
    workspace = 12,
    monitor = "HDMI-A-1",
    persistent = true,
    default_name = "​2",
})

hl.workspace_rule({
    workspace = 13,
    monitor = "HDMI-A-1",
    persistent = true,
    default_name = "​3",
})

hl.workspace_rule({
    workspace = 14,
    monitor = "HDMI-A-1",
    persistent = true,
    default_name = "​4",
})

hl.workspace_rule({
    workspace = 15,
    monitor = "HDMI-A-1",
    persistent = true,
    default_name = "​5",
})

hl.workspace_rule({
    workspace = 16,
    monitor = "HDMI-A-1",
    default_name = "​6",
})

hl.workspace_rule({
    workspace = 17,
    monitor = "HDMI-A-1",
    default_name = "​7",
})

hl.workspace_rule({
    workspace = 18,
    monitor = "HDMI-A-1",
    default_name = "​8",
})

hl.workspace_rule({
    workspace = 19,
    monitor = "HDMI-A-1",
    default_name = "​9",
})

hl.workspace_rule({
    workspace = 20,
    monitor = "HDMI-A-1",
    default_name = "​10",
})







--##################

--## MY PROGRAMS ###

--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

-- Set programs that you use

local terminal = "kitty"

--$fileManager = nemo

local fileManager = "nautilus"

local menu = "~/.config/hypr/scripts/open-hyprlauncher.sh"

--################

--## AUTOSTART ###

--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)

-- Or execute your favorite apps at launch like this:

-- exec-once = $terminal

-- exec-once = nm-applet &

-- exec-once = waybar & hyprpaper & firefox

-- Desktop notifications daemon. Without this, apps may fall back to opening

-- their own notification window instead of a small floating popup.






--exec-once = dunst

--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hypr.land/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("QT_QPA_PLATFORMTHEME", "gtk3")

hl.env("QT_STYLE_OVERRIDE", "Fusion")

hl.env("XMODIFIERS", "@im=fcitx")

--##################

--## PERMISSIONS ###

--##################

-- See https://wiki.hypr.land/Configuring/Permissions/

-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly

-- for security reasons

-- ecosystem {

--   enforce_permissions = 1

-- }

-- permission = /usr/(bin|local/bin)/grim, screencopy, allow

-- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow

-- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hypr.land/Configuring/Variables/

-- https://wiki.hypr.land/Configuring/Variables/#general

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 20,
        border_size = 2,
        -- https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
        --layout = scrolling
        col = {
            active_border = { colors = { "rgba(FDFDFDaa)", "rgba(898989ee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
    },
})

hl.config({
    scrolling = {
        column_width = 0.5,
        follow_focus = true,
        focus_fit_method = 1,
        explicit_column_widths = "0.333, 0.5, 0.667, 1.0",
        direction = "right",
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#decoration

hl.config({
    decoration = {
        rounding = 10,
        rounding_power = 2,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        -- https://wiki.hypr.land/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 8,
            passes = 3,
            ignore_opacity = true,
            vibrancy = 0.1696,
        },
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#animations

hl.config({
    animations = {
        enabled = true,
    },
})

-- Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
hl.curve("easeOutQuint", { type = "bezier", points = { {0.23, 1}, {0.32, 1} } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1} } })
hl.curve("linear", { type = "bezier", points = { {0, 0}, {1, 1} } })
hl.curve("almostLinear", { type = "bezier", points = { {0.5, 0.5}, {0.75, 1} } })
hl.curve("quick", { type = "bezier", points = { {0.15, 0}, {0.1, 1} } })

-- Default animations, see https://wiki.hypr.land/Configuring/Animations/
hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7, bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Workspace-Rules/

-- "Smart gaps" / "No gaps when only"

-- uncomment all if you wish to use that.

-- workspace = w[tv1], gapsout:0, gapsin:0

-- workspace = f[1], gapsout:0, gapsin:0

-- windowrule {

--     name = no-gaps-wtv1

--     match:float = false

--     match:workspace = w[tv1]

--

--     border_size = 0

--     rounding = 0

-- }

--

-- windowrule {

--     name = no-gaps-f1

--     match:float = false

--     match:workspace = f[1]

--

--     border_size = 0

--     rounding = 0

-- }

-- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more

hl.config({
    dwindle = {
        --    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        preserve_split = true,
        -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Master-Layout/ for more

hl.config({
    master = {
        new_status = "master",
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#misc

hl.config({
    misc = {
        force_default_wallpaper = -1,
        -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = false,
        -- If true disables the random hyprland logo / anime girl background. :(
    },
})

--############

--## INPUT ###

--############

-- https://wiki.hypr.land/Configuring/Variables/#input

hl.config({
    input = {
        kb_layout = "us",
        kb_variant = "altgr-intl",
        follow_mouse = 1,
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = false,
        },
    },
})

-- See https://wiki.hypr.land/Configuring/Gestures

hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

-- Example per-device config

-- See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

--##################

--## KEYBINDINGS ###

--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

local mainMod = "SUPER"

-- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "Return", hl.dsp.exec_cmd("kitty"))

hl.bind(mainMod .. " + " .. "Escape", hl.dsp.exec_cmd("~/.config/hypr/scripts/power-menu-wlogout.sh"))

hl.bind(mainMod .. " + " .. "L", hl.dsp.exec_cmd("pidof hyprlock >/dev/null 2>&1 || hyprlock"))

hl.bind(mainMod .. " + " .. "BackSpace", hl.dsp.exec_cmd("~/.config/hypr/scripts/clipboard-clear.sh"))

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Delete", hl.dsp.exec_cmd("~/.config/hypr/scripts/shutdown-menu.sh"))

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("nautilus"))

--bind = $mainMod, F, togglefloating,

hl.bind(mainMod .. " + " .. "R", hl.dsp.exec_cmd("~/.config/hypr/scripts/open-hyprlauncher.sh"))

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle

hl.bind(mainMod .. " + " .. "J", hl.dsp.layout("togglesplit"))

-- dwindle

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

hl.bind("ALT" .. " + " .. "TAB", hl.dsp.window.cycle_next())

hl.bind("ALT + SHIFT" .. " + " .. "TAB", hl.dsp.window.cycle_next({ next = false }))

--bind = ALT, TAB, bringactivetotop

hl.bind("SUPER" .. " + " .. "F", hl.dsp.window.fullscreen())

-- fullscreen total

hl.bind("SUPER + SHIFT" .. " + " .. "F", hl.dsp.window.fullscreen())

-- maximized respetando barras

--bind = SUPER SHIFT, SPACE, togglefloating

--bind = SUPER SHIFT, C, centerwindow, 1

hl.bind("SUPER + SHIFT" .. " + " .. "P", hl.dsp.window.pin())

-- Cambiar al workspace local N del monitor en foco con mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.exec_cmd("~/.config/hypr/scripts/ws-goto.sh 1"))

hl.bind(mainMod .. " + " .. 2, hl.dsp.exec_cmd("~/.config/hypr/scripts/ws-goto.sh 2"))

hl.bind(mainMod .. " + " .. 3, hl.dsp.exec_cmd("~/.config/hypr/scripts/ws-goto.sh 3"))

hl.bind(mainMod .. " + " .. 4, hl.dsp.exec_cmd("~/.config/hypr/scripts/ws-goto.sh 4"))

hl.bind(mainMod .. " + " .. 5, hl.dsp.exec_cmd("~/.config/hypr/scripts/ws-goto.sh 5"))

hl.bind(mainMod .. " + " .. 6, hl.dsp.exec_cmd("~/.config/hypr/scripts/ws-goto.sh 6"))

hl.bind(mainMod .. " + " .. 7, hl.dsp.exec_cmd("~/.config/hypr/scripts/ws-goto.sh 7"))

hl.bind(mainMod .. " + " .. 8, hl.dsp.exec_cmd("~/.config/hypr/scripts/ws-goto.sh 8"))

hl.bind(mainMod .. " + " .. 9, hl.dsp.exec_cmd("~/.config/hypr/scripts/ws-goto.sh 9"))

hl.bind(mainMod .. " + " .. 0, hl.dsp.exec_cmd("~/.config/hypr/scripts/ws-goto.sh 10"))

-- Mover ventana activa al workspace local N del monitor en foco

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.exec_cmd("~/.config/hypr/scripts/ws-goto.sh --move 1"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.exec_cmd("~/.config/hypr/scripts/ws-goto.sh --move 2"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.exec_cmd("~/.config/hypr/scripts/ws-goto.sh --move 3"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.exec_cmd("~/.config/hypr/scripts/ws-goto.sh --move 4"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.exec_cmd("~/.config/hypr/scripts/ws-goto.sh --move 5"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.exec_cmd("~/.config/hypr/scripts/ws-goto.sh --move 6"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.exec_cmd("~/.config/hypr/scripts/ws-goto.sh --move 7"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.exec_cmd("~/.config/hypr/scripts/ws-goto.sh --move 8"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.exec_cmd("~/.config/hypr/scripts/ws-goto.sh --move 9"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.exec_cmd("~/.config/hypr/scripts/ws-goto.sh --move 10"))

-- Alternar foco entre monitores con mainMod + TAB

hl.bind(mainMod .. " + " .. "TAB", hl.dsp.exec_cmd("~/.config/hypr/scripts/focus-monitor.sh"))

-- Mover ventana en foco al monitor vecino (no-op si no hay monitor en esa dirección)

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "left", hl.dsp.exec_cmd("~/.config/hypr/scripts/move-window-dir.sh left"))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "right", hl.dsp.exec_cmd("~/.config/hypr/scripts/move-window-dir.sh right"))

-- Example special workspace (scratchpad)

hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind(mainMod .. " + " .. "D", hl.dsp.window.move({ workspace = "e+0" }))

-- Scroll only through the workspaces of the focused monitor with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.exec_cmd("~/.config/hypr/scripts/ws-cycle.sh next"))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.exec_cmd("~/.config/hypr/scripts/ws-cycle.sh prev"))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Multimedia keys

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("~/.config/waybar/scripts/audio-osd.sh output raise"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("~/.config/waybar/scripts/audio-osd.sh output lower"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("~/.config/waybar/scripts/audio-osd.sh output mute"), { locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("~/.config/waybar/scripts/audio-osd.sh input mute"), { locked = true })

hl.bind("F13", hl.dsp.exec_cmd("~/.config/waybar/scripts/audio-osd.sh input mute"), { locked = true })

hl.bind("code:191", hl.dsp.exec_cmd("~/.config/waybar/scripts/audio-osd.sh input mute"), { locked = true })

--bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+

--bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

-- Requires playerctl

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("swayosd-client --playerctl next"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("swayosd-client --playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("swayosd-client --playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("swayosd-client --playerctl prev"), { locked = true })

-- rofi

hl.bind(mainMod .. " + " .. "Space", hl.dsp.exec_cmd("rofi -show window"))

hl.bind(mainMod .. " + " .. "A", hl.dsp.exec_cmd("~/.config/hypr/scripts/webapp-menu.sh --menu"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "W", hl.dsp.exec_cmd("~/.config/hypr/scripts/wallpaper-picker.sh"))

-- system cut/copy/paste

hl.bind("SUPER" .. " + " .. "X", hl.dsp.exec_cmd("~/.config/hypr/scripts/super-cut.sh"))

hl.bind("SUPER" .. " + " .. "C", hl.dsp.exec_cmd("~/.config/hypr/scripts/super-copy.sh"))

hl.bind("SUPER" .. " + " .. "V", hl.dsp.exec_cmd("~/.config/hypr/scripts/super-paste.sh"))

hl.bind("SUPER + ALT" .. " + " .. "V", hl.dsp.exec_cmd("~/.config/hypr/scripts/imgpush-abigail.sh"))

-- clipboard history: cliphist + custom GTK picker




hl.bind("SUPER + SHIFT" .. " + " .. "V", hl.dsp.exec_cmd("~/.config/hypr/scripts/desktop-picker-gtk.py clipboard"))

hl.bind("SUPER" .. " + " .. "period", hl.dsp.exec_cmd("~/.config/hypr/scripts/desktop-picker-gtk.py emoji"))

-- Swallow Ctrl+; so external apps/input methods cannot open their own clipboard popup.

hl.bind("CTRL" .. " + " .. "semicolon", hl.dsp.exec_cmd("true"))

-- screenshots

hl.bind("ALT" .. " + " .. "S", hl.dsp.exec_cmd("flameshot gui"))

hl.bind("Print", hl.dsp.exec_cmd("flameshot gui"))

-- Notification Center

-- bind = $mainMod, N, exec, swaync-client -t -sw

-- Control Center

hl.bind(mainMod .. " + " .. "N", hl.dsp.exec_cmd("~/.config/control-center/lnx-control-center"))

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

-- See https://wiki.hypr.land/Configuring/Window-Rules/ for more

-- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrules that are useful

hl.window_rule({
    name  = "suppress-maximize-events",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})

-- Control center floating panel

hl.window_rule({
    name  = "control-center-panel",
    match = {
        class = "dev.ritch.ControlCenter",
    },
    float = true,
    pin = true,
    size = { 420, 760 },
    move = { 1470, 42 },
})

-- Hyprland-run windowrule

hl.window_rule({
    name  = "move-hyprland-run",
    match = {
        class = "hyprland-run",
    },
    move = { 20, "monitor_h-120" },
    float = true,
})

hl.layer_rule({
    match = {
        namespace = "logout_dialog",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "logout_dialog",
    },
    ignore_alpha = 0.0,
})

hl.layer_rule({
    match = {
        namespace = "logout_dialog",
    },
    dim_around = true,
})

hl.layer_rule({
    match = {
        namespace = "logout_dialog",
    },
    blur_popups = true,
})

hl.layer_rule({
    match = {
        namespace = "lnx-df-clipboard-panel",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "lnx-df-clipboard-panel",
    },
    ignore_alpha = 0.15,
})

hl.layer_rule({
    match = {
        namespace = "lnx-df-emoji-panel",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "lnx-df-emoji-panel",
    },
    ignore_alpha = 0.15,
})

hl.config({
    cursor = {
        no_hardware_cursors = true,
    },
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("~/.config/waybar/scripts/start-waybar.sh")
    hl.exec_cmd("~/.config/waybar/scripts/audio-devices.sh --restore")
    hl.exec_cmd("test -x \"" .. os.getenv("HOME") .. "/.local/bin/fcitx5-no-tray\" && \"" .. os.getenv("HOME") .. "/.local/bin/fcitx5-no-tray\"")
    hl.exec_cmd("command -v awww-daemon >/dev/null 2>&1 && awww-daemon || command -v swww-daemon >/dev/null 2>&1 && swww-daemon")
    hl.exec_cmd("test -x/usr/lib/hyprpolkitagent/hyprpolkitagent &&/usr/lib/hyprpolkitagent/hyprpolkitagent")
    hl.exec_cmd("command -v hyprlauncher >/dev/null 2>&1 && hyprlauncher --daemon")
    hl.exec_cmd("swaync")
    hl.exec_cmd("qpwgraph")
    hl.exec_cmd("command -v swayosd-server >/dev/null 2>&1 && swayosd-server")
    hl.exec_cmd("command -v solaar >/dev/null 2>&1 && solaar -w hide")
    hl.exec_cmd("~/.config/control-center/lnx-control-center --daemon")
    hl.exec_cmd("~/.config/hypr/scripts/update-emoji-data.sh")
    hl.exec_cmd("wl-paste --type text --watch cliphist -max-items 20 store")
    hl.exec_cmd("wl-paste --type image --watch cliphist -max-items 20 store")
end)
