font_family               CaskaydiaCoveNerdFont
bold_font                 CaskaydiaCoveNerdFont
italic_font_family        CaskaydiaCoveNerdFont
bold_italic_font_family   CaskaydiaCoveNerdFont

font_size 20.0


disable_ligatures never

# Primary terminal theme. To switch back to the secondary dark theme, replace
# this include with: include themes/gentle-dark-secondary.conf
include themes/dark.conf

shell /usr/bin/fish
