[General]
ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""
Font="Open Sans"
FontSize="12"
KeyboardSize="0.38"
RoundCorners="22"
Locale=""
HourFormat="HH:mm"
DateFormat="dddd d"
HeaderText=""

BackgroundPlaceholder="Backgrounds/current-wallpaper.jpg"
Background="Backgrounds/current-background.mp4"
BackgroundSpeed="1.0"
PauseBackground="false"
DimBackground="0.28"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

HeaderTextColor="#f6f7fb"
DateTextColor="#d6d9e0"
TimeTextColor="#f7f7f8"
FormBackgroundColor="#16181c"
BackgroundColor="#16181c"
DimBackgroundColor="#0b0c0f"
LoginFieldBackgroundColor="#111317"
PasswordFieldBackgroundColor="#111317"
LoginFieldTextColor="#f5f6f7"
PasswordFieldTextColor="#f5f6f7"
UserIconColor="#f5f6f7"
PasswordIconColor="#f5f6f7"
PlaceholderTextColor="#8f949e"
WarningColor="#f2c879"
LoginButtonTextColor="#0d0f12"
LoginButtonBackgroundColor="#f5f5f5"
SystemButtonsIconsColor="#d7dbe3"
SessionButtonTextColor="#d7dbe3"
VirtualKeyboardButtonTextColor="#d7dbe3"
DropdownTextColor="#0d0f12"
DropdownSelectedBackgroundColor="#f1f3f5"
DropdownBackgroundColor="#d7dbe3"
HighlightTextColor="#0d0f12"
HighlightBackgroundColor="#f1f3f5"
HighlightBorderColor="transparent"
HoverUserIconColor="#ffffff"
HoverPasswordIconColor="#ffffff"
HoverSystemButtonsIconsColor="#ffffff"
HoverSessionButtonTextColor="#ffffff"
HoverVirtualKeyboardButtonTextColor="#ffffff"

PartialBlur="true"
FullBlur="false"
BlurMax="12"
Blur="2.2"
HaveFormBackground="true"
FormPosition="center"

VirtualKeyboardPosition="center"

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"
ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

TranslatePlaceholderUsername="user"
TranslatePlaceholderPassword="password"
TranslateLogin="unlock"
TranslateLoginFailedWarning=""
TranslateCapslockWarning="caps lock"
TranslateSuspend="sleep"
TranslateHibernate="hibernate"
TranslateReboot="restart"
TranslateShutdown="shutdown"
TranslateSessionSelection="session"
TranslateVirtualKeyboardButtonOn="keyboard"
TranslateVirtualKeyboardButtonOff="keyboard"
