set -g mouse on
set -g history-limit 50000

bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"

set -g status-style fg=colour250,bg=colour235
set -g status-left-length 30
set -g status-right-length 60
set -g status-left '#[fg=colour81]#S '
set -g status-right '#[fg=colour246]%Y-%m-%d #[fg=colour39]%H:%M '
