set -g mouse on
set -g history-limit 50000

bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"
bind c new-window \; move-window -r

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -g bell-action any
set -g visual-bell off
setw -g monitor-bell on

set -g status-position top
set -g status-interval 1
set -g status-justify absolute-centre
set -g status-style fg=#BBBBBB,bg=#191919

set -g message-style fg=#191919,bg=#C7CCD6
set -g mode-style fg=#191919,bg=#E5C07B

set -g pane-border-style fg=#505050
set -g pane-active-border-style fg=#C7CCD6
set -g pane-border-status off
set -g pane-border-format ''

set -g status-left-length 24
set -g status-right-length 0
set -g status-left '#[fg=#C7CCD6,bg=#191919,bold] 空 #[fg=#191919,bg=#191919]'
set -g status-right ''

set -g window-status-separator ''
set -g window-status-format '#[fg=#9E9E9E,bg=#191919] #W '
set -g window-status-current-format '#[fg=#191919,bg=#C7CCD6,bold] #W '

set -g window-status-bell-style fg=#191919,bg=#E06C75
